server:
  port: 8081
  address: 0.0.0.0 # Écoute sur toutes les interfaces réseau

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3307/patientdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose tous les endpoints Actuator
  endpoint:
    health:
      show-details: always # Affiche les détails pour /actuator/health
  info:
    app:
      name: "Patients Service"
      description: "Service de gestion des Patients"
      version: "1.0.0"



# Configuration Springdoc
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method 